name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_alB6aOCXG3nySWZrVGOQnx9O
      VERCEL_PROJECT_ID: prj_dhMJoQA1ufKVOmYSDhzVOciWRpTk
    steps:
      - uses: actions/checkout@v4
      - run: npx vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
